# Generated by Django 2.2.5 on 2020-02-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_set', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=20)),
                ('card_rarity', models.CharField(max_length=20)),
                ('card_mana_cost', models.IntegerField()),
                ('card_shield', models.IntegerField(default=0)),
                ('card_image', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=50)),
                ('deck_author', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('deck_description', models.CharField(max_length=500)),
                ('card1', models.CharField(max_length=100)),
                ('card2', models.CharField(max_length=100)),
                ('card3', models.CharField(max_length=100)),
                ('card4', models.CharField(max_length=100)),
                ('card5', models.CharField(max_length=100)),
                ('card6', models.CharField(max_length=100)),
                ('card7', models.CharField(max_length=100)),
                ('card8', models.CharField(max_length=100)),
                ('card9', models.CharField(max_length=100)),
                ('card10', models.CharField(max_length=100)),
            ],
        ),
    ]
