# Generated by Django 2.2.5 on 2020-02-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_PW',
            field=models.CharField(default='X', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card1', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card10', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card2', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card3', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card4', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card5', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card6', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card7', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card8', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_deck_card9', to='build_finder.Cards'),
        ),
    ]
