# Generated by Django 2.2.5 on 2020-02-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_finder', '0004_auto_20200213_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='card_mana_cost',
        ),
        migrations.AddField(
            model_name='cards',
            name='card_color',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_text',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_toughness',
            field=models.IntegerField(default=0),
        ),
    ]
