# Generated by Django 2.2.5 on 2020-02-16 19:43

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('build_finder', '0005_auto_20200213_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_video_link',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='deck',
            name='game_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='deck',
            name='create_date',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
