# Generated by Django 3.0.3 on 2020-05-01 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('build_finder', '0007_auto_20200501_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
#        migrations.AlterField(
#            model_name='deck',
#            name='create_date',
#            field=models.DateTimeField(default=django.utils.timezone.now),
#        ),
    ]
