# Generated by Django 3.0.3 on 2020-05-16 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_finder', '0008_auto_20200501_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_power',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_shield',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_text',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_toughness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='added_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='combo_card2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_combo_card2', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='combo_card3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_finder_combo_card3', to='build_finder.Cards'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='combo_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
